//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class 客戶聯絡人
    {
        public int Id { get; set; }
        public int 客戶Id { get; set; }
        [Required]
        [StringLength(20, ErrorMessage = "{0} 的長度至少必須為 {2} ~ {1} 個字元。", MinimumLength = 3)]
        public string 職稱 { get; set; }
        [Required]
        [StringLength(20, ErrorMessage = "{0} 的長度至少必須為 {2} ~ {1} 個字元。", MinimumLength = 2)]
        public string 姓名 { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [RegularExpression("\\d{4}-\\d{6}", ErrorMessage = "手機格式不正確( e.g. 0911-111111 )")]
        public string 手機 { get; set; }
        [Required]
        [StringLength(12, ErrorMessage = "{0} 的長度至少必須為 {2} ~ {1} 個字元。", MinimumLength = 8)]
        public string 電話 { get; set; }
    
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}
