//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class 客戶銀行資訊
    {
        public int Id { get; set; }
        public int 客戶Id { get; set; }
        [Required]
        [StringLength(20, ErrorMessage = "{0} 的長度至少必須為 {2} ~ {1} 個字元。", MinimumLength = 3)]
        public string 銀行名稱 { get; set; }
        [Required]
        [Range(1000, 9000, ErrorMessage = "{0} 的值至少必須為 {1} ~ {2} 數字。")]
        public int 銀行代碼 { get; set; }
        [Required]
        [Range(1000, 9000, ErrorMessage = "{0} 的值至少必須為 {1} ~ {2} 數字。")]
        public Nullable<int> 分行代碼 { get; set; }
        [Required]
        [StringLength(20, ErrorMessage = "{0} 的長度至少必須為 {2} ~ {1} 個字元。", MinimumLength = 3)]
        public string 帳戶名稱 { get; set; }
        [Required]
        [StringLength(20, ErrorMessage = "{0} 的長度至少必須為 {2} ~ {1} 個字元。", MinimumLength = 5)]
        public string 帳戶號碼 { get; set; }
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}
